server:
  port: 8079

spring:
  data:
    # MongoDB 配置项，对应 MongoProperties 类
    mongodb:
      host: 192.168.3.102
      port: 27017
      database: mydb2
#      username: test01
#      password: password01
      # 上述属性，也可以只配置 uri
